### ISSUE TITLE
running as docker container on a remote machine

### ISSUE THREAD

**Issue by ssbarnea** [adasq/gerrit-native-notifications#10]
Any plans to make it work using a docker instance which could run on another host than your desktop, monitor multiple gerrit servers and push notifications back to the user?

Somehow monitoring 5 gerrit servers event stream will clearly put a signifiant load on a laptop, especially as gerrit event logs are not filtered server side.

**Comment by adasq** [comment]
It's more client side project, rather than server. No plans for such an exotic use case. The foundation of the project was ordinary: 1 gerrit events source stream --> 1 developer.

But still if you would like to reuse this piece of code, you can split this project into two services:

1. server side - load 5 stream and filter its content based o rules (https://github.com/adasq/gerrit-native-notifications/blob/master/src/main.ts#L17),
2. client side - take an output from 1. and build notifications based on it.

That might not be complex, as overall structure is based on a streams.

**Comment by adasq** [comment]
Closing...
